name: Deployment

on:
  push:
    branches:
      - main

jobs:
  deployment:
    runs-on: ubuntu-latest

    steps:
      image: kingdragox99/Steam-Ban-Checker-Discord-Bot
      stage: deploy

      - name: Deployment OVH
          script: node index.js
              ## Intialize the git-ftp - After First push git ftp init comment so it will not intalize everytime
              - git ftp init -u $FTP_DEPLOY_USER --branch main --remote-root $FTP_PROJECT --verbose --key deployer.key --insecure sftp://$FTP_DEPLOY_HOST
              - git config git-ftp.url "sftp://$FTP_DEPLOY_HOST/$FTP_PROJECT"
              - git config git-ftp.password "$FTP_DEPLOY_PASSWORD"
              - git config git-ftp.user "$FTP_DEPLOY_USER"
              ## Push Code into Production Server
              - git ftp push --remote-root /$FTP_PROJECT/ -vv --insecure --key deployer.key --verbose --user $FTP_DEPLOY_USER sftp://$FTP_DEPLOY_HOST --passwd $FTP_DEPLOY_PASSWORD
              ## Connect the server and chnage directory and start js file for socket connection
              - ssh $FTP_DEPLOY_USER@$FTP_DEPLOY_HOST "cd FTP_PROJECT && node index.js"
